[versions]
agp = "9.3.2"
libxposed = "102.0.0"
libxposed-service = "102.0.0"

[libraries]
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "libxposed" }
libxposed-service = { group = "io.github.libxposed", name = "service", version.ref = "libxposed-service" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }